---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: https://www.eventbrite.com/e/cocina-214s-annual-running-of-the-chihuahuas-tickets-44995960128
sections:
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/shop
  label: Shop
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
  templates:
  - catering
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.28
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.28
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.28'
